#!/usr/bin/env bash
# sourced when an interactive shell is spawned. Use to customize the feel of
# your terminal, but scripts run outside the terminal may not use this setup

# User-customizable section
# Add your personal customizations here

