#!/bin/zsh
# sourced when you login to your computer. Changes here need a restart to take
# effect. These commands should never print output, as it may cause issues with
# automation running the script.

# Load brew, which adds the brew bin to PATH
eval "$(/opt/homebrew/bin/brew shellenv)"

# do a non-interactive mise activation to set up shims for tools so they can be available globally in scripts not available
eval "$(mise activate --shims)"

# Source all profile.d scripts (environment setup)
for script in "${DOTFILES_DIR}"/_home/profile.d/*.sh(N); do
  source "$script"
done
