#!/bin/zsh
# sourced when you login to your computer. Changes here need a restart to take
# effect. These commands should never print output, as it may cause issues with
# automation running the script.

# Load brew, which adds the brew bin to PATH
eval "$(/opt/homebrew/bin/brew shellenv)"

# do a non-interactive mise activation to set up shims for tools so they can be available globally
mise activate --shims

### managed by automation ###
eval "$($HOME/src/nsheaps/dotfiles/bin/dotfiles init)"
### end managed by automation ###
