#!/bin/zsh
# sourced when an interactive shell is spawned. Use to customize the feel of
# your terminal, but scripts run outside the terminal may not use this setup

# Enable comments in interactive shells (allows copy-pasting commands with comments)
setopt interactivecomments

# .zshenv is loaded before anything else, including macos path setup using /etc/paths (which then trump stuff in zshenv)
# .zprofile is loaded at login shells (when macos boots)
# .zshrc is loaded at non-login interactive shells (when you open a terminal)
#   in vscode, zshrc may be loaded again

# User-customizable section
# Add your personal customizations here

### managed by automation ###
eval "$($HOME/src/nsheaps/dotfiles/bin/dotfiles init)"
### end managed by automation ###

# Lazy-load (autoload) Zsh function files from a directory.
ZFUNCDIR=${ZDOTDIR:-$HOME}/.zfunctions
fpath=($ZFUNCDIR $fpath)
autoload -Uz $ZFUNCDIR/*(.:t)

# Create an amazing Zsh config using antidote plugins.

# Set the root name of the plugins files (.txt and .zsh) antidote will use.
zsh_plugins="${HOME}/.zsh_plugins"
# Ensure the .zsh_plugins.txt file exists so you can add plugins.
[[ -f ${zsh_plugins}.txt ]] || touch ${zsh_plugins}.txt

# Lazy-load antidote from its functions directory.
fpath=(/opt/homebrew/opt/antidote/share/antidote/functions $fpath)
autoload -Uz antidote

# Generate a new static file whenever .zsh_plugins.txt is updated.
if [[ ! ${zsh_plugins}.zsh -nt ${zsh_plugins}.txt ]]; then
  antidote bundle <${zsh_plugins}.txt >|${zsh_plugins}.zsh
fi

# Source your static plugins file.
source ${zsh_plugins}.zsh


if [[ -d "/Users/nathan.heaps/src/nsheaps/dotfiles/_home/interactive.d" ]]; then
  for file in $(find -L "/Users/nathan.heaps/src/nsheaps/dotfiles/_home/interactive.d" -type f -name "*.sh" | sort); do
    source "$file"
  done
fi
